(()=>{'use strict';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n);
let rates={},economy=true,loaded=false,loading=null,lastRows=[];
const session=()=>{try{return JSON.parse(sessionStorage.getItem('bpma_local_session_v1')||'{}')}catch{return {}}};
const admin=()=>session().role==='admin';
async function api(path,method='GET',body){const c=window.BPMA_SUPABASE_CONFIG;let auth=window.BPMA_AUTH?.loadSession?.();if(!auth?.access_token)throw new Error('Entre novamente para continuar.');if(Number(auth.expires_at||0)<=Date.now()+30000)auth=await window.BPMA_AUTH.refresh(auth);const res=await fetch(c.url.replace(/\/$/,'')+'/rest/v1/'+path,{method,headers:{apikey:c.publishableKey,Authorization:'Bearer '+auth.access_token,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=representation'},...(body!==undefined?{body:JSON.stringify(body)}:{})});const text=await res.text();let data;try{data=JSON.parse(text)}catch{data={message:text}}if(!res.ok)throw new Error(data?.message||'Não foi possível salvar. Confira a instalação SQL 5.0.');return data;}
async function load(){if(loaded)return;if(loading)return loading;loading=(async()=>{try{const data=await api('bpma5_settings?select=key,value');rates={};for(const r of data||[]){if(/^ufr_\d{4}$/.test(r.key)&&Number(r.value)>0)rates[r.key.slice(4)]=Number(r.value);if(r.key==='economy')economy=r.value!==false;}loaded=true;updateCard();}finally{loading=null}})();return loading;}
function total(rows){let reais=0,units=0;const missing=new Set();for(const r of rows){const n=Math.max(0,Number(r.stats?.ambientais?.ufrPb)||0);units+=n;if(!n)continue;const year=String(r.stats?.dataServico||r.finalizedAt||r.createdAt||'').slice(0,4);if(!rates[year])missing.add(/^\d{4}$/.test(year)?year:'data do serviço');else reais+=n*rates[year];}return {units,reais,missing:[...missing]};}
function card(rows,icon){lastRows=rows;const n=total(rows).units;queueMicrotask(()=>{load().catch(()=>{});updateCard()});return `<div class="stats37-card ufr50-card"><button type="button" data-ufr-toggle aria-label="Alternar UFRPB e reais">${icon}<span><small data-ufr-title>UFRPB aplicadas</small><b data-ufr-value>${new Intl.NumberFormat('pt-BR').format(n)}</b><small class="ufr50-hint">Alternar ⇄</small></span></button>${admin()?'<button type="button" data-ufr-config title="Configurar valor de 1 UFRPB" aria-label="Configurar valor de 1 UFRPB">⚙</button>':''}</div>`;}
let reaisMode=false;
function updateCard(){const value=document.querySelector('[data-ufr-value]'),title=document.querySelector('[data-ufr-title]');if(!value)return;const x=total(lastRows);title.textContent=reaisMode?'Equivalente em reais':'UFRPB aplicadas';value.textContent=reaisMode?(x.missing.length?'Valor pendente':money(x.reais)):new Intl.NumberFormat('pt-BR',{maximumFractionDigits:3}).format(x.units);const width=value.parentElement.clientWidth||150;value.style.fontSize=Math.min(innerWidth<=700?24:30,Math.max(11,Math.floor(width/(Math.max(1,value.textContent.length)*.60))))+'px';document.querySelector('[data-ufr-toggle]').title=x.missing.length?'Configure UFRPB: '+x.missing.join(', '):'Alternar UFRPB e reais';}
function dialog(html){document.getElementById('bpma50-dialog')?.remove();const d=document.createElement('dialog');d.id='bpma50-dialog';d.innerHTML=html;document.body.append(d);d.showModal();d.querySelector('[data-close]')?.addEventListener('click',()=>d.close());d.addEventListener('close',()=>d.remove());return d;}
async function config(){if(!admin())return;const d=dialog('<h3>Valor de 1 UFRPB</h3><p>Informe o valor oficial para o ano de referência.</p><form><label>Ano<input name="ano" type="number" min="2000" max="2100" required></label><label>Valor em R$<input name="valor" type="text" inputmode="decimal" placeholder="0,00" required></label><label class="economy50"><input type="checkbox" name="economia"> Modo economia de imagens no envio</label><p data-rate-list></p><p role="status"></p><div class="actions"><button type="button" data-close>Fechar</button><button type="submit">Salvar</button></div></form>');const f=d.querySelector('form'),status=d.querySelector('[role=status]');f.ano.value=new Date().getFullYear();f.economia.checked=economy;const sync=()=>{f.valor.value=rates[f.ano.value]?String(rates[f.ano.value]).replace('.',','):'';d.querySelector('[data-rate-list]').textContent=Object.entries(rates).map(([y,v])=>y+': '+money(v)).join(' · ')};f.ano.addEventListener('change',sync);try{await load();sync();f.economia.checked=economy}catch{status.textContent='Instale ATUALIZACAO_5_0.sql no Supabase antes de salvar.'}
f.onsubmit=async e=>{e.preventDefault();const y=Number(f.ano.value),v=Number(f.valor.value.trim().replace(/\s/g,'').replace(/^R\$/,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.'));if(!Number.isInteger(y)||y<2000||y>2100||!Number.isFinite(v)||v<=0){status.textContent='Informe ano e valor positivos válidos.';return;}const btn=f.querySelector('[type=submit]');btn.disabled=true;try{await api('bpma5_settings?on_conflict=key','POST',[{key:'ufr_'+y,value:v,updated_at:new Date().toISOString()},{key:'economy',value:f.economia.checked,updated_at:new Date().toISOString()}]);rates[y]=v;economy=f.economia.checked;loaded=true;updateCard();sync();status.textContent='Configuração salva para todos os usuários.'}catch(err){status.textContent=err.message}finally{btn.disabled=false}};}
async function trash(record,restore=false){if(!admin())throw new Error('Somente Admin.');if(record.tipo==='CPU')return api('rpc/bpma5_trash_report','POST',{report_id:record.id,restore});const current=await window.BPMA_LOCAL_REPORTS.get(record.id);if(!current)throw new Error('Relatório local não encontrado.');const dados={...current.dados};if(restore)delete dados.trash50;else dados.trash50={at:new Date().toISOString(),by:session().id};return window.BPMA_LOCAL_REPORTS.put({...current,dados});}
async function showTrash(){if(!admin())return;const d=dialog('<h3>Lixeira de relatórios</h3><p>CPU: Supabase. BO/RFA: neste aparelho. A restauração devolve o relatório às listas e aos indicadores aplicáveis.</p><div data-trash-list>Carregando…</div><p role="status"></p><button type="button" data-close>Fechar</button>');try{const [cpu,local]=await Promise.all([window.BPMA_CPU.listTrash(),window.BPMA_LOCAL_REPORTS.list()]);const rows=[...cpu,...local.filter(r=>r.dados?.trash50)];const list=d.querySelector('[data-trash-list]');list.innerHTML=rows.map((r,i)=>`<div class="trash50-row"><span><b>${esc(r.numero)}</b><small>${esc(r.tipo)} · ${esc(r.autor)} · ${esc(String(r.dados?.trash50?.at||'').slice(0,10))}</small></span><button type="button" data-restore50="${i}">Restaurar</button></div>`).join('')||'Lixeira vazia.';list.onclick=async e=>{const b=e.target.closest('[data-restore50]');if(!b)return;b.disabled=true;try{await trash(rows[Number(b.dataset.restore50)],true);b.closest('.trash50-row').remove();window.dispatchEvent(new Event('bpma50-reports-changed'));}catch(err){d.querySelector('[role=status]').textContent=err.message;b.disabled=false}};}catch(err){d.querySelector('[data-trash-list]').textContent=err.message}}
document.addEventListener('click',e=>{if(e.target.closest('[data-ufr-toggle]')){reaisMode=!reaisMode;updateCard()}if(e.target.closest('[data-ufr-config]'))config();if(e.target.closest('[data-trash50-open]'))showTrash()});
document.addEventListener('DOMContentLoaded',()=>{if(window.BPMA_AUTH?.loadSession?.()?.access_token)load().catch(()=>{})});
window.addEventListener('resize',updateCard);
window.BPMA50={load,card,total,trash,showTrash,isEconomy:()=>economy};
})();
